// flow-typed signature: ed6f9e840b377dbcfa7c1af0e329d9a7
// flow-typed version: <<STUB>>/babel-plugin-transform-export-extensions_v^6.8.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-export-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-export-extensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-export-extensions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-export-extensions/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-export-extensions/lib/index'>;
}
